# Generated by Django 5.0.3 on 2025-04-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room_id'], name='chat_messag_room_id_cee780_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='chat_messag_created_b6b51c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['topic'], name='chat_room_topic_i_98b160_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='chat_room_name_8fdd04_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['description'], name='chat_room_descrip_af2f47_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='chat_topic_name_29901e_idx'),
        ),
    ]
